# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ASP.NET Core Demo - Build and deploy ASP.Net Core app 

on:
  push:
    branches:
      - 'sesion-03'

    paths:
    - '.github/workflows/azure-webdeploy.yml'
    - 'material/WebApp'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.200'

    - name: Build with dotnet
      run: dotnet build material/WebApp/WebApp.csproj --configuration Release

    - name: dotnet publish
      run: dotnet publish material/WebApp/WebApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'my-aspnet-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_WebApp }}
        package: ${{env.DOTNET_ROOT}}/myapp 